Repository minos-framework/minos-python, pull requests merged in 2022-04, with the labels that each got.

#356 0.6.1
  packages/core/minos-microservice-common/HISTORY.md
  packages/core/minos-microservice-common/minos/common/__init__.py
  packages/core/minos-microservice-common/minos/common/launchers.py
  packages/core/minos-microservice-common/pyproject.toml
  packages/core/minos-microservice-common/tests/test_common/test_launchers.py
  packages/plugins/minos-broker-kafka/HISTORY.md
  packages/plugins/minos-broker-kafka/minos/plugins/kafka/__init__.py
  packages/plugins/minos-broker-kafka/minos/plugins/kafka/subscriber.py
  packages/plugins/minos-broker-kafka/pyproject.toml
  packages/plugins/minos-broker-kafka/tests/test_kafka/test_subscriber.py
Labels: release

#358 0.6.x
  packages/core/minos-microservice-common/HISTORY.md
  packages/core/minos-microservice-common/minos/common/__init__.py
  packages/core/minos-microservice-common/minos/common/launchers.py
  packages/core/minos-microservice-common/pyproject.toml
  packages/core/minos-microservice-common/tests/test_common/test_launchers.py
  packages/plugins/minos-broker-kafka/HISTORY.md
  packages/plugins/minos-broker-kafka/minos/plugins/kafka/__init__.py
  packages/plugins/minos-broker-kafka/minos/plugins/kafka/subscriber.py
  packages/plugins/minos-broker-kafka/pyproject.toml
  packages/plugins/minos-broker-kafka/tests/test_kafka/test_subscriber.py
Labels: documentation

#366 #363 - Discovery Kong documentation
  packages/plugins/minos-discovery-kong/README.md
Labels: enhancement

#375 #373 - Kong subscription
  packages/core/minos-microservice-networks/minos/networks/decorators/definitions/abc.py
  packages/core/minos-microservice-networks/minos/networks/decorators/definitions/broker.py
  packages/core/minos-microservice-networks/minos/networks/decorators/definitions/http/abc.py
  packages/core/minos-microservice-networks/minos/networks/decorators/definitions/periodic.py
  packages/core/minos-microservice-networks/minos/networks/discovery/clients/abc.py
  packages/core/minos-microservice-networks/minos/networks/discovery/connectors.py
  packages/core/minos-microservice-networks/tests/services/commands.py
  packages/core/minos-microservice-networks/tests/services/queries.py
  packages/core/minos-microservice-networks/tests/test_networks/test_decorators/test_api.py
  packages/core/minos-microservice-networks/tests/test_networks/test_decorators/test_collectors.py
  packages/core/minos-microservice-networks/tests/test_networks/test_decorators/test_definitions/test_abc.py
  packages/core/minos-microservice-networks/tests/test_networks/test_discovery/test_clients/test_abc.py
  packages/core/minos-microservice-networks/tests/test_networks/test_discovery/test_connectors.py
  packages/core/minos-microservice-networks/tests/utils.py
  packages/plugins/minos-discovery-kong/README.md
  packages/plugins/minos-discovery-kong/minos/plugins/kong/__init__.py
  packages/plugins/minos-discovery-kong/minos/plugins/kong/client.py
  packages/plugins/minos-discovery-kong/minos/plugins/kong/discovery.py
  packages/plugins/minos-discovery-kong/minos/plugins/kong/middleware.py
  packages/plugins/minos-discovery-kong/pyproject.toml
  packages/plugins/minos-discovery-kong/tests/__init__.py
  packages/plugins/minos-discovery-kong/tests/test_config.yml
  packages/plugins/minos-discovery-kong/tests/test_config_no_auth.yml
  packages/plugins/minos-discovery-kong/tests/test_kong/test_client.py
  packages/plugins/minos-discovery-kong/tests/test_kong/test_discovery.py
  packages/plugins/minos-discovery-kong/tests/test_kong/test_middleware.py
  packages/plugins/minos-discovery-kong/tests/utils.py
  packages/plugins/minos-http-aiohttp/minos/plugins/aiohttp/requests.py
  packages/plugins/minos-http-aiohttp/tests/test_aiohttp/test_requests.py
  packages/plugins/minos-router-graphql/minos/plugins/graphql/decorators.py
  packages/plugins/minos-router-graphql/tests/test_graphql/test_decorators.py
  packages/plugins/minos-router-graphql/tests/utils.py
Labels: enhancement

#368 #367 - Add `DatabaseClient`
  packages/core/minos-microservice-aggregate/minos/aggregate/events/repositories/pg.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/pg/abc.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/pg/api.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/pg/readers.py
  packages/core/minos-microservice-aggregate/minos/aggregate/transactions/repositories/pg.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_events/test_repositories/test_pg.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_abc.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_queries.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_readers.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_writers.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_transactions/test_repositories/test_pg.py
  packages/core/minos-microservice-aggregate/tests/utils.py
  packages/core/minos-microservice-common/minos/common/__init__.py
  packages/core/minos-microservice-common/minos/common/config/v1.py
  packages/core/minos-microservice-common/minos/common/config/v2.py
  packages/core/minos-microservice-common/minos/common/database/__init__.py
  packages/core/minos-microservice-common/minos/common/database/abc.py
  packages/core/minos-microservice-common/minos/common/database/clients/__init__.py
  packages/core/minos-microservice-common/minos/common/database/clients/abc.py
  packages/core/minos-microservice-common/minos/common/database/clients/aiopg.py
  packages/core/minos-microservice-common/minos/common/database/clients/exceptions.py
  packages/core/minos-microservice-common/minos/common/database/locks.py
  packages/core/minos-microservice-common/minos/common/database/pools.py
  packages/core/minos-microservice-common/minos/common/locks.py
  packages/core/minos-microservice-common/minos/common/pools.py
  packages/core/minos-microservice-common/minos/common/setup.py
  packages/core/minos-microservice-common/minos/common/testing.py
  packages/core/minos-microservice-common/tests/config/v1.yml
  packages/core/minos-microservice-common/tests/config/v2.yml
  packages/core/minos-microservice-common/tests/test_common/test_database/test_abc.py
  packages/core/minos-microservice-common/tests/test_common/test_database/test_clients/__init__.py
  packages/core/minos-microservice-common/tests/test_common/test_database/test_clients/test_abc.py
  packages/core/minos-microservice-common/tests/test_common/test_database/test_clients/test_aiopg.py
  packages/core/minos-microservice-common/tests/test_common/test_database/test_locks.py
  packages/core/minos-microservice-common/tests/test_common/test_database/test_pools.py
  packages/core/minos-microservice-common/tests/test_common/test_testing.py
  packages/core/minos-microservice-common/tests/utils.py
  packages/core/minos-microservice-networks/minos/networks/brokers/collections/queues/pg.py
  packages/core/minos-microservice-networks/minos/networks/brokers/handlers/impl.py
  packages/core/minos-microservice-networks/minos/networks/brokers/subscribers/filtered/validators/duplicates/pg.py
  packages/core/minos-microservice-networks/minos/networks/brokers/subscribers/queued/queues/pg.py
  packages/core/minos-microservice-networks/minos/networks/http/connectors.py
  packages/core/minos-microservice-networks/tests/test_networks/test_brokers/test_collections/test_queues/test_pg.py
  packages/core/minos-microservice-networks/tests/test_networks/test_brokers/test_subscribers/test_queued/test_queues/test_pg.py
  packages/core/minos-microservice-saga/minos/saga/executions/saga.py
  packages/core/minos-microservice-saga/minos/saga/manager.py
  packages/core/minos-microservice-saga/tests/utils.py
Labels: databases, minos-microservice-common

#396 #43 - Implement circuit breaker for `aiopg` connection failures
  packages/core/minos-microservice-common/minos/common/database/clients/abc.py
  packages/core/minos-microservice-common/minos/common/pools.py
  packages/core/minos-microservice-common/minos/common/testing/database/clients.py
  packages/core/minos-microservice-common/tests/test_common/test_database/test_clients/test_abc.py
  packages/core/minos-microservice-networks/minos/networks/brokers/pools.py
  packages/plugins/minos-database-aiopg/minos/plugins/aiopg/clients.py
  packages/plugins/minos-database-aiopg/tests/test_aiopg/test_clients.py
  packages/plugins/minos-database-lmdb/minos/plugins/lmdb/clients.py
Labels: minos-database-aiopg

#394 #390 - Kong Discovery JWT expiration
  packages/plugins/minos-discovery-kong/README.md
  packages/plugins/minos-discovery-kong/minos/plugins/kong/client.py
  packages/plugins/minos-discovery-kong/minos/plugins/kong/discovery.py
  packages/plugins/minos-discovery-kong/minos/plugins/kong/utils.py
  packages/plugins/minos-discovery-kong/poetry.lock
  packages/plugins/minos-discovery-kong/pyproject.toml
  packages/plugins/minos-discovery-kong/tests/test_config.yml
  packages/plugins/minos-discovery-kong/tests/test_kong/test_client.py
  packages/plugins/minos-discovery-kong/tests/test_kong/test_discovery.py
  packages/plugins/minos-discovery-kong/tests/test_kong/test_utils.py
Labels: enhancement

#408 0.7.0.dev2 (2)
  packages/plugins/minos-database-lmdb/minos/plugins/lmdb/clients.py
  packages/plugins/minos-discovery-kong/minos/plugins/kong/__init__.py
  packages/plugins/minos-router-graphql/minos/plugins/graphql/handlers.py
Labels: release
