Repository minos-framework/minos-python, pull requests merged in 2022-02, with the labels that each got.

#138 Update README.md
  README.md
Labels: documentation

#141 #139 - update `black`
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/pg/writers.py
  packages/core/minos-microservice-aggregate/poetry.lock
  packages/core/minos-microservice-aggregate/pyproject.toml
  packages/core/minos-microservice-common/minos/common/launchers.py
  packages/core/minos-microservice-common/poetry.lock
  packages/core/minos-microservice-common/pyproject.toml
  packages/core/minos-microservice-cqrs/poetry.lock
  packages/core/minos-microservice-cqrs/pyproject.toml
  packages/core/minos-microservice-saga/minos/saga/definitions/steps/conditional.py
  packages/core/minos-microservice-saga/poetry.lock
  packages/core/minos-microservice-saga/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: miscellaneous

#142 #140 - Improve README's quickstart
  README.md
Labels: documentation

#146 #97 create `minos-discovery-minos` plugin
  .github/workflows/minos-discovery-minos-publish.yml
  .github/workflows/minos-discovery-minos-tests.yml
  Makefile
  README.md
  packages/core/minos-microservice-networks/minos/networks/__init__.py
  packages/core/minos-microservice-networks/minos/networks/discovery/__init__.py
  packages/core/minos-microservice-networks/minos/networks/discovery/clients/__init__.py
  packages/core/minos-microservice-networks/minos/networks/discovery/clients/abc.py
  packages/core/minos-microservice-networks/minos/networks/discovery/clients/memory.py
  packages/core/minos-microservice-networks/tests/test_config.yml
  packages/core/minos-microservice-networks/tests/test_networks/test_discovery/test_clients/test_memory.py
  packages/core/minos-microservice-networks/tests/test_networks/test_discovery/test_connectors.py
  packages/plugins/minos-discovery-minos/AUTHORS.md
  packages/plugins/minos-discovery-minos/HISTORY.md
  packages/plugins/minos-discovery-minos/LICENSE
  packages/plugins/minos-discovery-minos/Makefile
  packages/plugins/minos-discovery-minos/README.md
  packages/plugins/minos-discovery-minos/RUNTHETESTS.md
  packages/plugins/minos-discovery-minos/SETUP.md
  packages/plugins/minos-discovery-minos/docs/Makefile
  packages/plugins/minos-discovery-minos/docs/_static/style.css
  packages/plugins/minos-discovery-minos/docs/_templates/layout.html
  packages/plugins/minos-discovery-minos/docs/authors.md
  packages/plugins/minos-discovery-minos/docs/conf.py
  packages/plugins/minos-discovery-minos/docs/history.md
  packages/plugins/minos-discovery-minos/docs/index.md
  packages/plugins/minos-discovery-minos/docs/readme.md
  packages/plugins/minos-discovery-minos/docs/runthetests.md
  packages/plugins/minos-discovery-minos/docs/usage.md
  packages/plugins/minos-discovery-minos/minos/plugins/minos_discovery/__init__.py
  packages/plugins/minos-discovery-minos/minos/plugins/minos_discovery/client.py
  packages/plugins/minos-discovery-minos/poetry.lock
  packages/plugins/minos-discovery-minos/poetry.toml
  packages/plugins/minos-discovery-minos/pyproject.toml
  packages/plugins/minos-discovery-minos/setup.cfg
  packages/plugins/minos-discovery-minos/tests/test_minos_discovery/__init__.py
  packages/plugins/minos-discovery-minos/tests/test_minos_discovery/test_client.py
  pyproject.toml
Labels: minos-discovery-minos, plugin

#154 0.5.1
  packages/core/minos-microservice-aggregate/HISTORY.md
  packages/core/minos-microservice-aggregate/minos/aggregate/__init__.py
  packages/core/minos-microservice-aggregate/poetry.lock
  packages/core/minos-microservice-aggregate/pyproject.toml
  packages/core/minos-microservice-cqrs/HISTORY.md
  packages/core/minos-microservice-cqrs/minos/cqrs/__init__.py
  packages/core/minos-microservice-cqrs/poetry.lock
  packages/core/minos-microservice-cqrs/pyproject.toml
  packages/core/minos-microservice-networks/HISTORY.md
  packages/core/minos-microservice-networks/minos/networks/__init__.py
  packages/core/minos-microservice-networks/poetry.lock
  packages/core/minos-microservice-networks/pyproject.toml
  packages/core/minos-microservice-saga/HISTORY.md
  packages/core/minos-microservice-saga/minos/saga/__init__.py
  packages/core/minos-microservice-saga/poetry.lock
  packages/core/minos-microservice-saga/pyproject.toml
  packages/plugins/minos-broker-kafka/HISTORY.md
  packages/plugins/minos-broker-kafka/minos/plugins/kafka/__init__.py
  packages/plugins/minos-broker-kafka/poetry.lock
  packages/plugins/minos-broker-kafka/pyproject.toml
  packages/plugins/minos-discovery-minos/HISTORY.md
  packages/plugins/minos-discovery-minos/minos/plugins/minos_discovery/__init__.py
  packages/plugins/minos-discovery-minos/poetry.lock
  packages/plugins/minos-discovery-minos/pyproject.toml
  poetry.lock
Labels: release

#158 Add Docker commands to start a Postgres DB for the quickstart
  README.md
Labels: documentation

#161 #160 - Add dockerized environment for quickstart
  README.md
Labels: documentation

#166 #157 - Add `Condition.LIKE` operator to be used with the`find` method of `SnapshotRepository`
  packages/core/minos-microservice-aggregate/minos/aggregate/queries.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/pg/queries.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_queries.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_queries.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_readers.py
Labels: minos-microservice-aggregate

#164 #163 - Rename autogenerated "get" commands
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/refs/resolvers.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/services.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_entities/test_refs/test_resolvers.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_services.py
Labels: minos-microservice-aggregate

#165 #156 - Add `get_all` method to `SnapshotRepository`
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/collections.py
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/models.py
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/refs/models.py
  packages/core/minos-microservice-aggregate/minos/aggregate/events/fields.py
  packages/core/minos-microservice-aggregate/minos/aggregate/events/models.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/abc.py
  packages/core/minos-microservice-aggregate/minos/aggregate/value_objects.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_entities/test_models/test_root/test_base.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_entities/test_models/test_root/test_not_provided.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_abc.py
Labels: minos-microservice-aggregate

#173 0.5.2
  README.md
  packages/core/minos-microservice-aggregate/HISTORY.md
  packages/core/minos-microservice-aggregate/minos/aggregate/__init__.py
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/collections.py
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/models.py
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/refs/models.py
  packages/core/minos-microservice-aggregate/minos/aggregate/entities/refs/resolvers.py
  packages/core/minos-microservice-aggregate/minos/aggregate/events/fields.py
  packages/core/minos-microservice-aggregate/minos/aggregate/events/models.py
  packages/core/minos-microservice-aggregate/minos/aggregate/queries.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/abc.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/pg/queries.py
  packages/core/minos-microservice-aggregate/minos/aggregate/snapshots/services.py
  packages/core/minos-microservice-aggregate/minos/aggregate/transactions/services.py
  packages/core/minos-microservice-aggregate/minos/aggregate/value_objects.py
  packages/core/minos-microservice-aggregate/pyproject.toml
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_entities/test_models/test_root/test_base.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_entities/test_models/test_root/test_not_provided.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_entities/test_refs/test_resolvers.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_queries.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_abc.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_queries.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_pg/test_readers.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_snapshots/test_services.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_transactions/test_services.py
  packages/core/minos-microservice-common/HISTORY.md
  packages/core/minos-microservice-common/minos/common/__init__.py
  packages/core/minos-microservice-common/minos/common/configuration/config.py
  packages/core/minos-microservice-common/pyproject.toml
  packages/core/minos-microservice-common/tests/test_common/test_configuration/test_config.py
  packages/core/minos-microservice-common/tests/test_config.yml
  packages/core/minos-microservice-networks/HISTORY.md
  packages/core/minos-microservice-networks/minos/networks/__init__.py
  packages/core/minos-microservice-networks/minos/networks/decorators/builders.py
  packages/core/minos-microservice-networks/minos/networks/decorators/definitions/periodic.py
  packages/core/minos-microservice-networks/pyproject.toml
  packages/core/minos-microservice-networks/tests/test_networks/test_decorators/test_builders.py
  packages/core/minos-microservice-saga/HISTORY.md
  packages/core/minos-microservice-saga/minos/saga/__init__.py
  packages/core/minos-microservice-saga/minos/saga/executions/commit.py
  packages/core/minos-microservice-saga/pyproject.toml
  packages/core/minos-microservice-saga/tests/test_saga/test_executions/test_commit.py
  packages/core/minos-microservice-saga/tests/test_saga/test_manager.py
Labels: release

#184 Fix README
  README.md
Labels: documentation

#181 #179 - Add `external_packages` argument
  packages/core/minos-microservice-common/minos/common/launchers.py
  packages/core/minos-microservice-common/tests/test_common/test_launchers.py
Labels: enhancement, minos-microservice-common

#206 #200 - Print error stack trace instead of warning
  packages/core/minos-microservice-networks/minos/networks/rest/handlers.py
Labels: enhancement

#207 #205 - tests for event get attr and get attrs
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_events/test_models.py
Labels: enhancement

#225 #224 - Event class modify get_attr & get_attrs by get_field & get_fields
  packages/core/minos-microservice-aggregate/minos/aggregate/events/models.py
  packages/core/minos-microservice-aggregate/tests/test_aggregate/test_events/test_models.py
Labels: enhancement
